<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Detail</name>
   <tag></tag>
   <elementGuidId>9d919e8c-2a81-475b-ab67-d06018546241</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='magang']/div[3]/div[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c3b38ea5-0417-4f9d-84a9-ee7753017902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex w-full justify-center items-center gap-x-3 text-center bg-gradient-to-tl from-blue-600 to-violet-600 shadow-md shadow-transparent hover:shadow-blue-700/50 border border-transparent text-white text-sm font-medium rounded-lg focus:outline-none focus:ring-1 focus:ring-blue-600 focus:ring-offset-1 focus:ring-offset-white py-3 px-6</value>
      <webElementGuid>e6b90901-84c2-45af-b885-1acfaeb0e9a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>detailMagang?magangId=6645a69abb1c3686860c0b5d</value>
      <webElementGuid>b39795e5-380c-46cf-8083-94ac9700d072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Detail</value>
      <webElementGuid>4b77f52f-6025-4baa-aff3-879442d8a908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;magang&quot;)/div[@class=&quot;flex flex-col cursor-pointer justify-start rounded-xl p-4 md:p-6 bg-white border border-gray-200 shadow-md hover:shadow-lg hover:-translate-y-2 transition-all duration-500 ease-in-out&quot;]/div[@class=&quot;flex justify-end pt-2&quot;]/a[@class=&quot;inline-flex w-full justify-center items-center gap-x-3 text-center bg-gradient-to-tl from-blue-600 to-violet-600 shadow-md shadow-transparent hover:shadow-blue-700/50 border border-transparent text-white text-sm font-medium rounded-lg focus:outline-none focus:ring-1 focus:ring-blue-600 focus:ring-offset-1 focus:ring-offset-white py-3 px-6&quot;]</value>
      <webElementGuid>64e86d1e-c565-44f6-b26c-947697ebc8a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='magang']/div[3]/div[4]/a</value>
      <webElementGuid>93dd3e9d-98f1-49db-8691-764ef94a450f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Detail')])[2]</value>
      <webElementGuid>ac7b9da0-ed6c-4a54-ba1b-a4e096b60b52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batas Akhir : 2025-10-15'])[1]/following::a[1]</value>
      <webElementGuid>6d85fc46-7144-4e0e-ab68-777d6e2865fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cyber Security'])[1]/following::a[1]</value>
      <webElementGuid>d56b1583-e93e-49a3-bbb9-a3165c834de2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'detailMagang?magangId=6645a69abb1c3686860c0b5d')]</value>
      <webElementGuid>72d7b27a-8891-4f6f-98ee-4ff2d1948612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]/a</value>
      <webElementGuid>81a67344-ae6d-4516-a0de-4d25f374b598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'detailMagang?magangId=6645a69abb1c3686860c0b5d' and (text() = 'Detail' or . = 'Detail')]</value>
      <webElementGuid>08b66ee0-bf17-41a2-b14e-b834d7f5552c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
